name: Build & Package GDExtension

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version tag (e.g. 0.1.0)
        required: true

jobs:
  build:
    strategy:
      matrix:
        target:
          - { platform: linux, arch: x86_64, os: ubuntu-22.04 }
          - { platform: windows, arch: x86_64, os: windows-latest }
        build_target_type: ["template_debug", "template_release"]
    runs-on:  ${{ matrix.target.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python and install SCons
        run: |
          python -m pip install --upgrade pip
          pip install scons

      - name: Install Linux dependencies
        if: matrix.target.platform == 'linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libbluetooth-dev

      - name: Cache scons cache
        uses: actions/cache@v4
        with:
          path: .scons_cache
          key: ${{ matrix.target.os }}-scons-cache-${{ matrix.target.platform }}-${{ matrix.target.arch }}

      - name: Build GDWiiInput
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache
        run: |
          mkdir -p ${{ github.workspace }}/build/addons/GDWiiInput/${{ matrix.target.platform }}
          scons target=${{ matrix.build_target_type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} out=${{ github.workspace }}/build/addons/GDWiiInput/${{ matrix.target.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GDWiiInput-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.build_target_type }}
          path: |
            ${{ github.workspace }}/build/**
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: GDWiiInput-v${{ github.event.inputs.version }}
          pattern: GDWiiInput-*
          delete-merged: true
