name: Build & Package GDExtension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 0.1.0
        required: true

env:
  ADDON_BUILD_DIR: build/addons/gdwiiinput
  ADDON_ZIP_ROOT: addons/gdwiiinput

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: ubuntu-latest
            platform: linux
            arch: x86_64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python and install SCons
        run: |
          python -m pip install --upgrade pip
          pip install scons
          scons --version

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libbluetooth-dev

      - name: Cache scons cache
        uses: actions/cache@v4
        with:
          path: .scons_cache
          key: ${{ runner.os }}-scons-cache-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Build extension
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache
        run: scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=template_release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: ${{ env.ADDON_BUILD_DIR }}

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare final addon folder
        run: |
          mkdir -p ${ADDON_BUILD_DIR}
          # Merge downloaded build artifacts into the build folder
          cp -r artifacts/build/addons/gdwiiinput/* ${ADDON_BUILD_DIR}/

      - name: Zip final addon
        run: |
          cd build
          zip -r ../GDWiiInput-v${{ github.event.inputs.version }}.zip addons/gdwiiinput

      - name: Upload final zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDWiiInput
          path: GDWiiInput-v${{ github.event.inputs.version }}.zip
