name: Manual Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 0.1)'
        required: true

env:
  LIBNAME: GDWiiInput
  BUILD_ADDON_DIR: build/addons/gdwiiinput
  ZIP_ROOT_DIR: addons/gdwiiinput

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-release
            os: windows-latest
            target: template_release
            platform: windows
            arch: x86_64
          - identifier: linux-release
            os: ubuntu-latest
            target: template_release
            platform: linux
            arch: x86_64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up SCons
        run: |
          python -m pip install scons
          scons --version

      - name: Install Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config libbluetooth-dev

      - name: Cache godot-cpp
        uses: actions/cache@v4
        with:
          path: godot-cpp
          key: ${{ runner.os }}-godot-cpp-${{ matrix.identifier }}
          restore-keys: |
            ${{ runner.os }}-godot-cpp-

      - name: Compile extension
        run: |
          scons target=${{ matrix.target }} platform=${{ matrix.platform }} arch=${{ matrix.arch }}

      - name: Move built library (Linux)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          mkdir -p ${{ env.BUILD_ADDON_DIR }}/linux
          mv demo/bin/*linux* ${{ env.BUILD_ADDON_DIR }}/linux/ || true
        shell: bash

      - name: Move built library (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: |
          mkdir -p ${{ env.BUILD_ADDON_DIR }}/windows
          powershell -Command "Move-Item -Path 'demo/bin/*windows*' -Destination '${{ env.BUILD_ADDON_DIR }}/windows/' -ErrorAction SilentlyContinue"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: ${{ env.BUILD_ADDON_DIR }}

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare addon folder
        run: |
          # Copy your existing addon files from build/addons/gdwiiinput to a temp folder
          cp -r build/addons/gdwiiinput addon-temp

          # Overlay the built platform folders from artifacts on top
          cp -r artifacts/*/linux addon-temp/linux || true
          cp -r artifacts/*/windows addon-temp/windows || true

      - name: Zip addon starting at addons/gdwiiinput folder
        run: |
          mkdir -p zip-root/addons
          mv addon-temp zip-root/addons/gdwiiinput
          cd zip-root
          zip -r ../GDWiiInput-v${{ github.event.inputs.version }}.zip addons/gdwiiinput

      - name: Upload final zip
        uses: actions/upload-artifact@v4
        with:
          name: GDWiiInput
          path: GDWiiInput-v${{ github.event.inputs.version }}.zip
